### ISSUE TITLE
Suggestion of installation guidelines

### ISSUE THREAD

**Issue by jhunchua** [adevait/hrm#1]
Hello,

It would be helpful for a simple installation guidelines

**Comment by trajchevska** [comment]
Thanks, @jhunchua! The readme is updated with installation guidelines. Cheers!

**Comment by jhunchua** [comment]
Suggestion of the installation steps.. I had a few problems when trying the steps mentioned on your guide. 

1.	Dedicate a domain/subdomain to the project and set up the virtual host accordingly.
2.	Create a database that will be used for the application purposes.
3.	Still in the command line, run composer install to install all dependencies, and then composer dump to autoload the needed files.
4.	Copy the .env.example file on the root of the app to a new file named .env. Update the database fields according to your local setup.
5.	Run in command line php artisan key:generate
6.	On the command line, run php artisan migrate to create the needed tables.
7.	Possible errors: if the app is not working at this point, there are probably some permission errors.
o	Check /storage permissions - the storage folder on the root of the app should be writable by the application. Make sure the permissions are set correctly.
o	Check /bootstrap/cache permissions - this folder should also be writable. Make sure the permissions are set correctly.
8.	At this point you should have the app up and running. Hit yourdomain/register to open the registration screen for creating an admin user. This is a one time setup and the credentials set here will be used for authenticating before using the system.

**Comment by trajchevska** [comment]
Thanks, @jhunchua! I just adjusted the readme according to your suggestions.
