### ISSUE TITLE
Login page UI not loading

### ISSUE THREAD

**Issue by jhunchua** [adevait/hrm#3]
UI not loading, errors below

GET http://localhost/css/app.css login:14
GET http://localhost/js/app.js login:99 
GET http://localhost/js/app.js login:99 

error 404
<link href="/css/app.css" rel="stylesheet">
<script src="/js/app.js"></script>

**Comment by trajchevska** [comment]
I assume this is a problem with your Laravel setup. Please make sure you've passed all of the steps described in the installation process and have created the virtual host properly. If all of that is completed well, there shouldn't be a problem with the UI.
