### ISSUE TITLE
yourdomain/register 

### ISSUE THREAD

**Issue by Dunrar** [adevait/hrm#37]
I tried installing the app locally on WampServer. Just copied the project folder to the .../wamp64/www folder and followed instructions from there. The tables have been created in the database. When I open http://localhost/hrm-master, I only get **Index of /hrm-master** followed by all the folders and files in the projects folder. 
Did I set something up the wrong way in the .env file?

**Comment by trajchevska** [comment]
You need to have a virtual host pointing to the `public` folder of the app in order to have it working. The easiest option would be starting a Laravel server by running `php artisan serve` in your root folder. Check [this](https://laravel.com/docs/5.6/installation#installing-laravel) for more info.
