### ISSUE TITLE
login email and password

### ISSUE THREAD

**Issue by asyraflan94** [adevait/hrm#44]
hi, sorry for disturb, but can I know the login email and password to access your system?

**Comment by davorminchorov** [comment]
@asyraflan94 from the readme file: 

> 8. At this point you should have the app up and running. Hit yourdomain/register to open the registration screen for creating an admin user. This is a one time setup and the credentials set here will be used for authenticating before using the system.

**Comment by asyraflan94** [comment]
noted, thx I'll try it now :)
